# Generated by Django 4.0.6 on 2023-04-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trish', '0004_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
