# Generated by Django 4.0.6 on 2023-05-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trish', '0014_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
