# Generated by Django 4.0.6 on 2023-05-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trish', '0015_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_date',
            new_name='comment_date',
        ),
    ]
